# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b85e612339033c6a3edfd075642ff9e"
name = "GA4 App"
handle = "ga4-app-2"
application_url = "https://varied-becoming-book-ic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cc-app-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
  "https://varied-becoming-book-ic.trycloudflare.com/auth/callback",
  "https://varied-becoming-book-ic.trycloudflare.com/auth/shopify/callback",
  "https://varied-becoming-book-ic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
