# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1468a45f6bfd3ca348dfcba91ccec42"
name = "demo-app"
handle = "demo-app-1010"
application_url = "https://eclipse-specific-intent-immediate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "learning-codecrew.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://eclipse-specific-intent-immediate.trycloudflare.com/auth/callback",
  "https://eclipse-specific-intent-immediate.trycloudflare.com/auth/shopify/callback",
  "https://eclipse-specific-intent-immediate.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
