# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e61cacf356fa0080de241c972c47df26"
name = "new-demo-app"
handle = "new-demo-app-10"
application_url = "https://tf-loss-scout-become.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "the-cashmare.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://tf-loss-scout-become.trycloudflare.com/auth/callback",
  "https://tf-loss-scout-become.trycloudflare.com/auth/shopify/callback",
  "https://tf-loss-scout-become.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
